name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Frontend to Cloudflare Pages
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Frontend
        run: pnpm --filter @assembled-brands/frontend build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: assembled-frontend-assets
          directory: packages/frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
