name: Deploy to Node Package Manager

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-frontend:
    name: Publish Frontend to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Frontend
        run: pnpm --filter @assembled-brands/frontend build

      - name: Publish to npm
        run: |
          cd packages/frontend
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
